### ISSUE TITLE
Stacktrace in console "Could not pass RespawnPlayerEvent$Impl to Plugin{id=deathpenalty, name=DeathPenalty, version=v1.1, authors=[RandomByte], source=/opt/infinitylite/./plugins/deathpenalty-v1.1.jar} org.spongepowered.api.text.TextTemplateArgumentException: Missing required argument in TextTemplate "xpLoss"."

### ISSUE THREAD

**Issue by ProsperCraft** [randombyte-developer/death-penalty#1]
https://gist.github.com/ProsperCraft/6ea8d8576d2046bb5678a0498c2dd3e3

**Comment by randombyte-developer** [comment]
Please backup the config and let it regenerate by deleting it. Then compare the deathMessage of both versions. There must be something missing regarding `xpLoss`.

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/2aea567c31b4cd61f8369644c89b5480

Here is our config, trying to negate the xp loss and only cost money.

**Comment by randombyte-developer** [comment]
Ah, ok, then please remove the `{xpLoss}` argument in the death message. It can't be replaced by the plugin with a value because xp loss is turned off.

**Comment by randombyte-developer** [comment]
@ProsperCraft Did it work?

**Comment by ProsperCraft** [comment]
works great thank you!
